services:
  php-fpm:
    build: .
    volumes:
      - ./app:/var/www/html
      - ./app/database:/var/www/html/database
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
